service: project-server-luminis

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 256
  timeout: 30
  stage: ${opt:stage, 'prod'}
  

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: project-server-luminis-${self:provider.stage}-layer
      description:  project-server-luminis-${self:provider.stage}-layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      include:
        - main.py
        - utils/**
        - schemas/**
        - routes/**
        - models/**
        - middlewares/**
        - functions/**
        - database/**
        - auth/**
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"
    
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}